---
title: "Final-Project"
author: "Tram Anh Hoang, Haitham Anbar, Maria Coronado, Erick Njue"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(here)
library(rio)
library(readr)
library(janitor)
library(tidyverse)

race <- import(here("data", "pagr_schools_ela_tot_raceethnicity_2122.csv")) %>% 
  clean_names() %>%
  as_tibble()
view(race)

attend <- import(here("data", "regularattenders_report_2122.csv")) %>% 
  clean_names() %>%
  as_tibble()
view(attend)
```


## Attendance data

```{r}
#Summarizing to check the existing student groups in the file
attendsum <- attend %>% 
 group_by(student_group) %>% 
  summarise()
attendsum


#Filtering the dataframe leaving only student groups related to race. 
attend1 <- attend %>% 
   filter(student_group == "American Indian/Alaska Native" |
          student_group == "Asian"|
          student_group == "Black/African American" |
          student_group == "Hispanic/Latino" |
          student_group == "Multi-Racial" |
          student_group == "Native Hawaiian/Pacific Islander" |
          student_group == "Underserved Races/Ethnicities" |
          student_group == "White")


#Removing rows without data
attend1 <- attend1%>% 
  filter(students_included != "*")
    
# Note: All schools with >95% and <5% regular attenders were eliminated. 
#These rows corresponded with schools where less than 9 students were included. 

dim(attend1)
view(attend1)
```

# Profficiency data
```{r}

racesum <- race %>% 
 group_by(student_group) %>% 
  summarise()


#Filtering the dataframe leaving only student groups related to race. 
race1 <- race %>% 
     filter(student_group == "American Indian/Alaskan Native" |
          student_group == "Asian"|
          student_group == "Black/African American" |
          student_group == "Hispanic/Latino" |
          student_group == "Multi-Racial" |
          student_group == "Pacific Islander" |
          student_group == "White") %>% 
  filter(number_proficient != "*" &
          number_proficient != "--")
view(race1)

race1 <- race1 %>% 
  as_tibble

race1$number_proficient <- as.numeric(as.character(race1$number_proficient))
race1

race2 <- race1 %>% 
 group_by(school_id, student_group) %>% 
 summarise(number_proficient1 = sum(number_proficient))

view(race2)

```

