---
title: "Final-Project"
author: "Tram Anh Hoang, Haitham Anbar, Maria Coronado, Erick Njue"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(here)
library(rio)
library(readr)
library(janitor)
library(tidyverse)

race <- import(here("data", "pagr_schools_ela_tot_raceethnicity_2122.csv")) %>% 
  clean_names() %>%
  as_tibble()
view(race)

attend <- import(here("data", "regularattenders_report_2122.csv")) %>% 
  clean_names() %>%
  as_tibble()
view(attend)
```


## Attendance data

```{r}
#Summarizing to check the existing student groups in the file
attendsum <- attend %>% 
 group_by(student_group) %>% 
  summarise()
attendsum


#Filtering the dataframe leaving only student groups related to race. 
attend1 <- attend %>% 
   filter(student_group == "American Indian/Alaska Native" |
          student_group == "Asian"|
          student_group == "Black/African American" |
          student_group == "Hispanic/Latino" |
          student_group == "Multi-Racial" |
          student_group == "Native Hawaiian/Pacific Islander" |
          student_group == "White") %>%
  mutate(student_group=recode(student_group,
                              "Native Hawaiian/Pacific Islander" = "Pacific Islander"))


#Removing rows without data
attend1 <- attend1%>% 
  filter(students_included != "*")
    
# Note: All schools with >95% and <5% regular attenders were eliminated. 
#These rows corresponded with schools where less than 9 students were included. 

dim(attend1)
view(attend1)
```

# Profficiency data
```{r}
#Finding the races considered in the file
racesum <- race %>% 
 group_by(student_group) %>% 
  summarise()


#Filtering the dataframe leaving only student groups related to race.
#Filtered again to remove rows without data on proficiency data
#Transformed number of participants to numeric and the filtered to all >= than 10 students. 
race1 <- race %>% 
   select(-grade_level) %>% 
     filter(student_group == "American Indian/Alaskan Native" |
          student_group == "Asian"|
          student_group == "Black/African American" |
          student_group == "Hispanic/Latino" |
          student_group == "Multi-Racial" |
          student_group == "Pacific Islander" |
          student_group == "White") %>% 
 filter(number_proficient != "*" &
        number_proficient != "--") %>% 
 transform(number_of_participants = as.numeric(number_of_participants)) %>% 
 filter(number_of_participants >= 10)
race1

#Transformed all columns to numbers to be able to compute them. The file had them as characters.
race2<- race1 %>% 
  transform(
    number_proficient = as.numeric(number_proficient), 
    percent_proficient_level_3_or_4 = as.numeric(percent_proficient_level_3_or_4),
    number_level_4 = as.numeric(number_level_4), 
    percent_level_4 = as.numeric(percent_level_4), 
    number_level_3 = as.numeric(number_level_3), 
    percent_level_3 = as.numeric(percent_level_3), 
    number_level_2 = as.numeric(number_level_2), 
    percent_level_2 = as.numeric(percent_level_2), 
    number_level_1 = as.numeric(number_level_1),
    percent_level_1 = as.numeric(percent_level_1), 
    participation_rate = as.numeric(participation_rate)
    )
race2
view(race2)

#Grouped data by school_id and student_group, summed the number of participants and number of proficient students, and re-calculate the percentage of proficient students.
race3 <- race2 %>% 
 group_by(district_id,school_id, student_group) %>% 
 summarise(number_proficient = sum(number_proficient),
           number_of_participants=sum(number_of_participants)) %>%
  mutate(percent_proficient = number_proficient/number_of_participants*100)

race3

```

# Joining 2 datasets

```{r}
#Check that 2 datasets have matching student groups
unique(attend1$student_group)
unique(race3$student_group)

#Join
attend_race <- left_join(attend1, race3, by=c("district_id"="district_id", "institution_id"="school_id", "student_group"="student_group")) %>%
  drop_na()

view(attend_race)
```


# Creating a summary table with percentage profficient by type of school
```{r}

#Pivot wider by student_group to have columns by races:
prof_by_race <- attend_race %>%
  group_by(institution_type, student_group) %>% 
  summarise(number_of_participants = sum(number_of_participants),
            number_proficient = sum(number_proficient)) %>% 
  mutate(percent_prof_race = (number_proficient/number_of_participants*100)) %>% 
  mutate(percent_prof_race = round(percent_prof_race, 2)) %>% 
 pivot_wider(names_from = "student_group",
 values_from = "percent_prof_race") %>% 
  clean_names()

#Doing an additional pivot longer followed by a pivot wider to make the table look good:
prof_percent_by_type_of_inst <- prof_by_race %>% 
  select(-number_of_participants, -number_proficient) %>%
  pivot_longer( cols = 2:7,
                names_to = "race",
                values_to = "values") %>% 
  drop_na() %>% 
  pivot_wider(names_from = "race",
  values_from = "values") %>% 
  clean_names()

view(prof_percent_by_type_of_inst)

<<<<<<< Updated upstream

```
=======
```{r}
attend_race %>%
  ggplot(aes(x=percent_regular_attenders, y=percent_proficient,group=student_group)) +
  geom_point() +
  geom_smooth(method='lm') +  
  facet_wrap(~student_group) +
  labs(title="Student Attendance and Proficiency Rate in English, Language, and Arts",
       subtitle="Data from Oregon Education Department",
       x="Rate of Regular Attendance (%)",
       y="Percentage of proficient students (%)")

?geom_smooth

```


>>>>>>> Stashed changes
